-- =============================================================================
-- 2. Starter recipe collection (112 recipes written for this project, 78 of them Indian)
-- Diet labels here were written for this project and checked by hand.
--   vegetarian = no meat, fish or eggs · eggetarian = vegetarian plus eggs
--   non_veg = eggs and chicken are fine, but no other meat or fish
--   gluten_free treats hing (asafoetida) as containing gluten: most hing is mixed with wheat flour
-- Recipes you add are labeled by AI (see 04_ai_tags.sql), which can also compare AI labels with these.
-- =============================================================================
INSERT INTO recipes (title, cuisine, minutes, servings, ingredients, steps,
                     vegetarian, eggetarian, non_veg, gluten_free, dairy_free, nut_free,
                     tagged_by, source, search_text)
VALUES
  ('Garlicky Spinach Scrambled Eggs', 'American', 10, 2, ARRAY['eggs', 'baby spinach', 'garlic', 'butter', 'salt', 'black pepper'],
   'Melt the butter in a pan over medium heat and soften the sliced garlic for a minute. Add the spinach and stir until just wilted. Pour in the beaten eggs, season, and stir gently until softly set.',
   false, true, true, true, false, true, 'starter', 'starter',
   'Garlicky Spinach Scrambled Eggs. American dish, 10 minutes. Ingredients: eggs, baby spinach, garlic, butter, salt, black pepper. Melt the butter in a pan over medium heat and soften the sliced garlic for a minute. Add the spinach and stir until just wilted. Pour in the beaten eggs, season, and stir gently until softly set.'),
  ('Chickpea and Spinach Curry', 'Indian', 30, 4, ARRAY['canned chickpeas', 'baby spinach', 'onion', 'garlic', 'canned tomatoes', 'coconut milk', 'curry powder', 'basmati rice'],
   'Start the rice. Fry the diced onion until golden, add garlic and curry powder for a minute, then the tomatoes and coconut milk. Add the drained chickpeas and simmer 15 minutes. Stir in the spinach until wilted and serve over rice.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Chickpea and Spinach Curry. Indian dish, 30 minutes. Ingredients: canned chickpeas, baby spinach, onion, garlic, canned tomatoes, coconut milk, curry powder, basmati rice. Start the rice. Fry the diced onion until golden, add garlic and curry powder for a minute, then the tomatoes and coconut milk. Add the drained chickpeas and simmer 15 minutes. Stir in the spinach until wilted and serve over rice.'),
  ('Lemon Herb Chicken Thighs', 'Mediterranean', 35, 4, ARRAY['chicken thighs', 'lemon', 'garlic', 'olive oil', 'oregano', 'salt', 'black pepper'],
   'Toss the chicken with olive oil, lemon zest and juice, crushed garlic, oregano, salt and pepper. Roast skin side up at 425°F (220°C) for about 30 minutes, until golden and cooked through. Rest 5 minutes before serving.',
   false, false, true, true, true, true, 'starter', 'starter',
   'Lemon Herb Chicken Thighs. Mediterranean dish, 35 minutes. Ingredients: chicken thighs, lemon, garlic, olive oil, oregano, salt, black pepper. Toss the chicken with olive oil, lemon zest and juice, crushed garlic, oregano, salt and pepper. Roast skin side up at 425°F (220°C) for about 30 minutes, until golden and cooked through. Rest 5 minutes before serving.'),
  ('Blistered Cherry Tomato Pasta', 'Italian', 20, 2, ARRAY['pasta', 'cherry tomatoes', 'garlic', 'olive oil', 'basil', 'parmesan'],
   'Boil the pasta. Meanwhile, cook the tomatoes in olive oil over high heat until they burst, then add sliced garlic. Toss with the drained pasta, a splash of pasta water, torn basil and grated parmesan.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Blistered Cherry Tomato Pasta. Italian dish, 20 minutes. Ingredients: pasta, cherry tomatoes, garlic, olive oil, basil, parmesan. Boil the pasta. Meanwhile, cook the tomatoes in olive oil over high heat until they burst, then add sliced garlic. Toss with the drained pasta, a splash of pasta water, torn basil and grated parmesan.'),
  ('Chicken Fajita Wraps', 'Mexican', 25, 4, ARRAY['chicken thighs', 'bell peppers', 'onion', 'tortillas', 'cumin', 'paprika', 'lemon', 'cilantro'],
   'Slice the chicken, peppers and onion into strips. Season with cumin and paprika and cook in a hot pan until charred and cooked through. Squeeze over lemon, then serve in warm tortillas with cilantro.',
   false, false, true, false, true, true, 'starter', 'starter',
   'Chicken Fajita Wraps. Mexican dish, 25 minutes. Ingredients: chicken thighs, bell peppers, onion, tortillas, cumin, paprika, lemon, cilantro. Slice the chicken, peppers and onion into strips. Season with cumin and paprika and cook in a hot pan until charred and cooked through. Squeeze over lemon, then serve in warm tortillas with cilantro.'),
  ('Veggie Fried Rice', 'Chinese', 20, 2, ARRAY['basmati rice', 'eggs', 'frozen peas', 'carrots', 'green onion', 'soy sauce'],
   'Use rice cooked earlier, ideally cold. Scramble the eggs in a hot oiled pan and set aside. Stir-fry diced carrot and peas, add the rice and fry until hot, then return the eggs with soy sauce and sliced green onion.',
   false, true, true, false, true, true, 'starter', 'starter',
   'Veggie Fried Rice. Chinese dish, 20 minutes. Ingredients: basmati rice, eggs, frozen peas, carrots, green onion, soy sauce. Use rice cooked earlier, ideally cold. Scramble the eggs in a hot oiled pan and set aside. Stir-fry diced carrot and peas, add the rice and fry until hot, then return the eggs with soy sauce and sliced green onion.'),
  ('Banana Peanut Butter Overnight Oats', 'Breakfast', 5, 1, ARRAY['oats', 'milk', 'bananas', 'peanut butter', 'honey'],
   'Stir the oats, milk, half a mashed banana and a spoon of peanut butter together in a jar. Refrigerate overnight. Top with the rest of the banana and a drizzle of honey.',
   true, true, true, false, false, false, 'starter', 'starter',
   'Banana Peanut Butter Overnight Oats. Breakfast dish, 5 minutes. Ingredients: oats, milk, bananas, peanut butter, honey. Stir the oats, milk, half a mashed banana and a spoon of peanut butter together in a jar. Refrigerate overnight. Top with the rest of the banana and a drizzle of honey.'),
  ('Greek Yogurt Breakfast Bowl', 'Breakfast', 5, 1, ARRAY['greek yogurt', 'oats', 'berries', 'honey'],
   'Spoon the yogurt into a bowl, then top with oats, fresh berries and a drizzle of honey.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Greek Yogurt Breakfast Bowl. Breakfast dish, 5 minutes. Ingredients: greek yogurt, oats, berries, honey. Spoon the yogurt into a bowl, then top with oats, fresh berries and a drizzle of honey.'),
  ('Cheesy Black Bean Quesadillas', 'Mexican', 15, 2, ARRAY['tortillas', 'canned black beans', 'cheddar cheese', 'bell peppers', 'salsa'],
   'Mash half the beans lightly. Fill each tortilla with beans, diced pepper and cheddar, then fold. Cook in a dry pan until crisp on both sides and the cheese melts. Serve with salsa.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Cheesy Black Bean Quesadillas. Mexican dish, 15 minutes. Ingredients: tortillas, canned black beans, cheddar cheese, bell peppers, salsa. Mash half the beans lightly. Fill each tortilla with beans, diced pepper and cheddar, then fold. Cook in a dry pan until crisp on both sides and the cheese melts. Serve with salsa.'),
  ('Creamy Tomato Soup', 'American', 30, 4, ARRAY['canned tomatoes', 'onion', 'garlic', 'vegetable broth', 'heavy cream', 'butter'],
   'Soften the onion and garlic in butter. Add the tomatoes and broth and simmer 20 minutes. Blend until smooth, then stir in the cream and season to taste.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Creamy Tomato Soup. American dish, 30 minutes. Ingredients: canned tomatoes, onion, garlic, vegetable broth, heavy cream, butter. Soften the onion and garlic in butter. Add the tomatoes and broth and simmer 20 minutes. Blend until smooth, then stir in the cream and season to taste.'),
  ('Pea and Mint Risotto', 'Italian', 35, 3, ARRAY['arborio rice', 'frozen peas', 'onion', 'vegetable broth', 'parmesan', 'butter', 'mint'],
   'Soften the onion in butter, add the rice and stir for a minute. Add hot broth a ladle at a time, stirring, for about 20 minutes. Stir in the peas, parmesan and chopped mint in the last few minutes.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Pea and Mint Risotto. Italian dish, 35 minutes. Ingredients: arborio rice, frozen peas, onion, vegetable broth, parmesan, butter, mint. Soften the onion in butter, add the rice and stir for a minute. Add hot broth a ladle at a time, stirring, for about 20 minutes. Stir in the peas, parmesan and chopped mint in the last few minutes.'),
  ('Two-Ingredient Banana Pancakes', 'Breakfast', 15, 1, ARRAY['bananas', 'eggs', 'cinnamon'],
   'Mash a ripe banana and whisk with two eggs and a pinch of cinnamon. Cook small pancakes in a lightly oiled pan over medium-low heat, flipping once.',
   false, true, true, true, true, true, 'starter', 'starter',
   'Two-Ingredient Banana Pancakes. Breakfast dish, 15 minutes. Ingredients: bananas, eggs, cinnamon. Mash a ripe banana and whisk with two eggs and a pinch of cinnamon. Cook small pancakes in a lightly oiled pan over medium-low heat, flipping once.'),
  ('Red Lentil Soup', 'Middle Eastern', 35, 4, ARRAY['red lentils', 'onion', 'carrots', 'garlic', 'cumin', 'vegetable broth', 'lemon'],
   'Soften the onion, carrot and garlic. Add cumin, the rinsed lentils and broth, and simmer 25 minutes until the lentils fall apart. Blend partly, then finish with lemon juice.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Red Lentil Soup. Middle Eastern dish, 35 minutes. Ingredients: red lentils, onion, carrots, garlic, cumin, vegetable broth, lemon. Soften the onion, carrot and garlic. Add cumin, the rinsed lentils and broth, and simmer 25 minutes until the lentils fall apart. Blend partly, then finish with lemon juice.'),
  ('Black Bean Stuffed Peppers', 'Tex-Mex', 40, 4, ARRAY['bell peppers', 'basmati rice', 'canned black beans', 'corn', 'cheddar cheese', 'salsa'],
   'Halve and seed the peppers. Mix cooked rice, beans, corn and salsa, then fill the peppers. Top with cheddar and bake at 400°F (200°C) for about 25 minutes.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Black Bean Stuffed Peppers. Tex-Mex dish, 40 minutes. Ingredients: bell peppers, basmati rice, canned black beans, corn, cheddar cheese, salsa. Halve and seed the peppers. Mix cooked rice, beans, corn and salsa, then fill the peppers. Top with cheddar and bake at 400°F (200°C) for about 25 minutes.'),
  ('Sesame Peanut Noodles', 'Thai-inspired', 20, 2, ARRAY['noodles', 'peanut butter', 'soy sauce', 'garlic', 'lemon', 'cucumber', 'green onion'],
   'Cook the noodles. Whisk peanut butter, soy sauce, grated garlic, lemon juice and a splash of hot water into a sauce. Toss with the noodles, then top with sliced cucumber and green onion.',
   true, true, true, false, true, false, 'starter', 'starter',
   'Sesame Peanut Noodles. Thai-inspired dish, 20 minutes. Ingredients: noodles, peanut butter, soy sauce, garlic, lemon, cucumber, green onion. Cook the noodles. Whisk peanut butter, soy sauce, grated garlic, lemon juice and a splash of hot water into a sauce. Toss with the noodles, then top with sliced cucumber and green onion.'),
  ('Shakshuka', 'North African', 25, 2, ARRAY['eggs', 'canned tomatoes', 'onion', 'bell peppers', 'garlic', 'paprika', 'cumin'],
   'Cook the onion and pepper until soft, add garlic and spices, then the tomatoes, and simmer 10 minutes. Make wells, crack in the eggs, cover and cook until the whites set.',
   false, true, true, true, true, true, 'starter', 'starter',
   'Shakshuka. North African dish, 25 minutes. Ingredients: eggs, canned tomatoes, onion, bell peppers, garlic, paprika, cumin. Cook the onion and pepper until soft, add garlic and spices, then the tomatoes, and simmer 10 minutes. Make wells, crack in the eggs, cover and cook until the whites set.'),
  ('Chicken and Rice Soup', 'American', 45, 4, ARRAY['chicken thighs', 'basmati rice', 'carrots', 'celery', 'onion', 'chicken broth'],
   'Simmer the chicken in the broth for 20 minutes, then remove and shred. Add diced onion, carrot, celery and the rice and cook 15 minutes. Return the chicken and season.',
   false, false, true, true, true, true, 'starter', 'starter',
   'Chicken and Rice Soup. American dish, 45 minutes. Ingredients: chicken thighs, basmati rice, carrots, celery, onion, chicken broth. Simmer the chicken in the broth for 20 minutes, then remove and shred. Add diced onion, carrot, celery and the rice and cook 15 minutes. Return the chicken and season.'),
  ('Caprese Salad', 'Italian', 10, 2, ARRAY['tomatoes', 'mozzarella', 'basil', 'olive oil', 'balsamic vinegar'],
   'Slice the tomatoes and mozzarella and arrange them overlapping with basil leaves. Drizzle with olive oil and balsamic, then season with salt and pepper.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Caprese Salad. Italian dish, 10 minutes. Ingredients: tomatoes, mozzarella, basil, olive oil, balsamic vinegar. Slice the tomatoes and mozzarella and arrange them overlapping with basil leaves. Drizzle with olive oil and balsamic, then season with salt and pepper.'),
  ('Migas', 'Tex-Mex', 20, 2, ARRAY['eggs', 'tortillas', 'onion', 'bell peppers', 'cheddar cheese', 'salsa'],
   'Cut the tortillas into strips and fry until crisp. Add diced onion and pepper and cook until soft. Pour in the beaten eggs and scramble, then finish with cheddar and salsa.',
   false, true, true, false, false, true, 'starter', 'starter',
   'Migas. Tex-Mex dish, 20 minutes. Ingredients: eggs, tortillas, onion, bell peppers, cheddar cheese, salsa. Cut the tortillas into strips and fry until crisp. Add diced onion and pepper and cook until soft. Pour in the beaten eggs and scramble, then finish with cheddar and salsa.'),
  ('Pesto Pasta with Peas', 'Italian', 15, 2, ARRAY['pasta', 'basil pesto', 'frozen peas', 'parmesan'],
   'Cook the pasta, adding the peas for the last 2 minutes. Drain, keeping a little water, then toss with pesto, a splash of the water and grated parmesan.',
   true, true, true, false, false, false, 'starter', 'starter',
   'Pesto Pasta with Peas. Italian dish, 15 minutes. Ingredients: pasta, basil pesto, frozen peas, parmesan. Cook the pasta, adding the peas for the last 2 minutes. Drain, keeping a little water, then toss with pesto, a splash of the water and grated parmesan.'),
  ('Crispy Chickpea Salad', 'Mediterranean', 20, 2, ARRAY['canned chickpeas', 'cherry tomatoes', 'cucumber', 'red onion', 'lemon', 'olive oil', 'feta'],
   'Pat the chickpeas dry and fry in olive oil until crisp. Toss with halved tomatoes, cucumber, thinly sliced red onion, lemon juice and crumbled feta.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Crispy Chickpea Salad. Mediterranean dish, 20 minutes. Ingredients: canned chickpeas, cherry tomatoes, cucumber, red onion, lemon, olive oil, feta. Pat the chickpeas dry and fry in olive oil until crisp. Toss with halved tomatoes, cucumber, thinly sliced red onion, lemon juice and crumbled feta.'),
  ('Dal Tadka', 'Indian', 35, 4, ARRAY['toor dal (arhar)', 'onion', 'tomatoes', 'garlic', 'ghee', 'cumin seeds (jeera)', 'turmeric (haldi)', 'red chili powder (lal mirch)', 'asafoetida (hing)', 'cilantro (hara dhania)'],
   'Rinse the dal and pressure-cook it with turmeric, salt and 3 cups of water for 3 to 4 whistles, or simmer for 30 minutes, until soft. Whisk it smooth. For the tadka, heat the ghee, crackle the cumin seeds and add a pinch of hing. Add sliced garlic and chopped onion and fry until golden, then the tomatoes and chili powder until soft. Pour the tadka over the dal, simmer 5 minutes and finish with cilantro.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Dal Tadka. Indian dish, 35 minutes. Ingredients: toor dal (arhar), onion, tomatoes, garlic, ghee, cumin seeds (jeera), turmeric (haldi), red chili powder (lal mirch), asafoetida (hing), cilantro (hara dhania). Rinse the dal and pressure-cook it with turmeric, salt and 3 cups of water for 3 to 4 whistles, or simmer for 30 minutes, until soft. Whisk it smooth. For the tadka, heat the ghee, crackle the cumin seeds and add a pinch of hing. Add sliced garlic and chopped onion and fry until golden, then the tomatoes and chili powder until soft. Pour the tadka over the dal, simmer 5 minutes and finish with cilantro.'),
  ('Tomato Moong Dal', 'Indian', 25, 3, ARRAY['moong dal', 'tomatoes', 'ghee', 'cumin seeds (jeera)', 'turmeric (haldi)', 'asafoetida (hing)', 'green chilies (hari mirch)', 'cilantro (hara dhania)', 'lemon'],
   'Rinse the moong dal and simmer it with turmeric, salt and 3 cups of water for about 20 minutes, until soft. Heat the ghee, crackle the cumin seeds and add the hing, slit green chilies and chopped tomatoes. Cook until the tomatoes break down. Stir this into the dal and simmer 3 minutes. Finish with lemon juice and cilantro.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Tomato Moong Dal. Indian dish, 25 minutes. Ingredients: moong dal, tomatoes, ghee, cumin seeds (jeera), turmeric (haldi), asafoetida (hing), green chilies (hari mirch), cilantro (hara dhania), lemon. Rinse the moong dal and simmer it with turmeric, salt and 3 cups of water for about 20 minutes, until soft. Heat the ghee, crackle the cumin seeds and add the hing, slit green chilies and chopped tomatoes. Cook until the tomatoes break down. Stir this into the dal and simmer 3 minutes. Finish with lemon juice and cilantro.'),
  ('Jeera Rice', 'Indian', 30, 3, ARRAY['basmati rice', 'ghee', 'cumin seeds (jeera)', 'bay leaf (tej patta)', 'salt'],
   'Rinse the rice until the water runs clear and soak it for 15 minutes. Heat the ghee, crackle the cumin seeds with the bay leaf, then add the drained rice and stir gently for a minute. Add 1¾ cups of water per cup of rice and some salt. Cover and cook on low for 12 minutes. Rest 5 minutes and fluff with a fork.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Jeera Rice. Indian dish, 30 minutes. Ingredients: basmati rice, ghee, cumin seeds (jeera), bay leaf (tej patta), salt. Rinse the rice until the water runs clear and soak it for 15 minutes. Heat the ghee, crackle the cumin seeds with the bay leaf, then add the drained rice and stir gently for a minute. Add 1¾ cups of water per cup of rice and some salt. Cover and cook on low for 12 minutes. Rest 5 minutes and fluff with a fork.'),
  ('Chana Masala', 'Indian', 35, 4, ARRAY['canned chickpeas (chole)', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'green chilies (hari mirch)', 'cumin seeds (jeera)', 'coriander powder (dhania)', 'turmeric (haldi)', 'garam masala', 'cilantro (hara dhania)'],
   'Crackle the cumin seeds in hot oil, then fry the chopped onion until deep golden. Add grated ginger, garlic and green chilies for a minute. Add the tomatoes, turmeric, coriander powder and salt and cook until the oil separates. Add the drained chickpeas and a cup of water, mash a few against the pan and simmer 15 minutes. Stir in the garam masala and top with cilantro.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Chana Masala. Indian dish, 35 minutes. Ingredients: canned chickpeas (chole), onion, tomatoes, ginger (adrak), garlic, green chilies (hari mirch), cumin seeds (jeera), coriander powder (dhania), turmeric (haldi), garam masala, cilantro (hara dhania). Crackle the cumin seeds in hot oil, then fry the chopped onion until deep golden. Add grated ginger, garlic and green chilies for a minute. Add the tomatoes, turmeric, coriander powder and salt and cook until the oil separates. Add the drained chickpeas and a cup of water, mash a few against the pan and simmer 15 minutes. Stir in the garam masala and top with cilantro.'),
  ('Palak Paneer', 'Indian', 35, 3, ARRAY['spinach (palak)', 'paneer', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'green chilies (hari mirch)', 'cumin seeds (jeera)', 'garam masala', 'fresh cream'],
   'Blanch the spinach for 2 minutes, cool it in cold water and blend it with the green chilies until smooth. Crackle the cumin seeds in oil, then fry the onion until golden. Add ginger, garlic and tomatoes and cook until soft. Stir in the spinach puree, garam masala and salt and simmer 5 minutes. Add cubed paneer and a spoon of cream and heat through.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Palak Paneer. Indian dish, 35 minutes. Ingredients: spinach (palak), paneer, onion, tomatoes, ginger (adrak), garlic, green chilies (hari mirch), cumin seeds (jeera), garam masala, fresh cream. Blanch the spinach for 2 minutes, cool it in cold water and blend it with the green chilies until smooth. Crackle the cumin seeds in oil, then fry the onion until golden. Add ginger, garlic and tomatoes and cook until soft. Stir in the spinach puree, garam masala and salt and simmer 5 minutes. Add cubed paneer and a spoon of cream and heat through.'),
  ('Aloo Gobi', 'Indian', 30, 4, ARRAY['potatoes (aloo)', 'cauliflower (gobi)', 'onion', 'tomatoes', 'ginger (adrak)', 'green chilies (hari mirch)', 'cumin seeds (jeera)', 'turmeric (haldi)', 'coriander powder (dhania)', 'garam masala', 'cilantro (hara dhania)'],
   'Crackle the cumin seeds in oil and fry the onion until soft. Add ginger, green chilies, turmeric and coriander powder, then the cubed potatoes and cauliflower florets with salt. Toss to coat, cover and cook on low for 15 minutes, stirring now and then. Add the chopped tomatoes and cook uncovered until the vegetables are tender. Finish with garam masala and cilantro.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Aloo Gobi. Indian dish, 30 minutes. Ingredients: potatoes (aloo), cauliflower (gobi), onion, tomatoes, ginger (adrak), green chilies (hari mirch), cumin seeds (jeera), turmeric (haldi), coriander powder (dhania), garam masala, cilantro (hara dhania). Crackle the cumin seeds in oil and fry the onion until soft. Add ginger, green chilies, turmeric and coriander powder, then the cubed potatoes and cauliflower florets with salt. Toss to coat, cover and cook on low for 15 minutes, stirring now and then. Add the chopped tomatoes and cook uncovered until the vegetables are tender. Finish with garam masala and cilantro.'),
  ('Kanda Poha', 'Indian', 20, 2, ARRAY['poha', 'onion', 'potato (aloo)', 'peanuts', 'mustard seeds (rai)', 'curry leaves (kadi patta)', 'green chilies (hari mirch)', 'turmeric (haldi)', 'lemon', 'cilantro (hara dhania)', 'sugar'],
   'Rinse the poha in a strainer and let it soften for 5 minutes. Fry the peanuts in oil until crisp and set them aside. In the same oil, crackle the mustard seeds with curry leaves and green chilies. Add the onion and diced potato and cook covered until the potato is tender. Add turmeric, the poha, salt and a pinch of sugar, toss gently and steam 2 minutes. Finish with the peanuts, lemon juice and cilantro.',
   true, true, true, true, true, false, 'starter', 'starter',
   'Kanda Poha. Indian dish, 20 minutes. Ingredients: poha, onion, potato (aloo), peanuts, mustard seeds (rai), curry leaves (kadi patta), green chilies (hari mirch), turmeric (haldi), lemon, cilantro (hara dhania), sugar. Rinse the poha in a strainer and let it soften for 5 minutes. Fry the peanuts in oil until crisp and set them aside. In the same oil, crackle the mustard seeds with curry leaves and green chilies. Add the onion and diced potato and cook covered until the potato is tender. Add turmeric, the poha, salt and a pinch of sugar, toss gently and steam 2 minutes. Finish with the peanuts, lemon juice and cilantro.'),
  ('Rava Upma', 'Indian', 20, 2, ARRAY['semolina (rava)', 'onion', 'mustard seeds (rai)', 'urad dal', 'curry leaves (kadi patta)', 'ginger (adrak)', 'green chilies (hari mirch)', 'ghee', 'cilantro (hara dhania)'],
   'Dry-roast the semolina until it smells nutty, then set it aside. Heat the ghee and crackle the mustard seeds and urad dal until golden. Add curry leaves, ginger, green chilies and onion and cook until soft. Pour in 2½ cups of water with salt and bring to a boil. Stream in the semolina while stirring, cover and cook on low for 3 minutes. Finish with cilantro.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Rava Upma. Indian dish, 20 minutes. Ingredients: semolina (rava), onion, mustard seeds (rai), urad dal, curry leaves (kadi patta), ginger (adrak), green chilies (hari mirch), ghee, cilantro (hara dhania). Dry-roast the semolina until it smells nutty, then set it aside. Heat the ghee and crackle the mustard seeds and urad dal until golden. Add curry leaves, ginger, green chilies and onion and cook until soft. Pour in 2½ cups of water with salt and bring to a boil. Stream in the semolina while stirring, cover and cook on low for 3 minutes. Finish with cilantro.'),
  ('Rajma Chawal', 'Indian', 45, 4, ARRAY['canned kidney beans (rajma)', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'cumin seeds (jeera)', 'coriander powder (dhania)', 'red chili powder (lal mirch)', 'garam masala', 'basmati rice'],
   'Start the rice. Crackle the cumin seeds in oil and fry the onion until deep golden. Add ginger and garlic, then the tomatoes, coriander powder, chili powder and salt, and cook into a thick masala. Add the drained kidney beans and 2 cups of water and simmer 20 minutes, mashing a few beans to thicken the gravy. Stir in the garam masala and serve over the rice.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Rajma Chawal. Indian dish, 45 minutes. Ingredients: canned kidney beans (rajma), onion, tomatoes, ginger (adrak), garlic, cumin seeds (jeera), coriander powder (dhania), red chili powder (lal mirch), garam masala, basmati rice. Start the rice. Crackle the cumin seeds in oil and fry the onion until deep golden. Add ginger and garlic, then the tomatoes, coriander powder, chili powder and salt, and cook into a thick masala. Add the drained kidney beans and 2 cups of water and simmer 20 minutes, mashing a few beans to thicken the gravy. Stir in the garam masala and serve over the rice.'),
  ('Masala Omelette', 'Indian', 10, 1, ARRAY['eggs', 'onion', 'tomatoes', 'green chilies (hari mirch)', 'cilantro (hara dhania)', 'turmeric (haldi)'],
   'Beat the eggs with a pinch of turmeric and salt. Stir in finely chopped onion, tomato, green chili and cilantro. Heat a little oil in a pan, pour in the eggs and cook on medium until the bottom is set. Fold or flip and cook 30 seconds more.',
   false, true, true, true, true, true, 'starter', 'starter',
   'Masala Omelette. Indian dish, 10 minutes. Ingredients: eggs, onion, tomatoes, green chilies (hari mirch), cilantro (hara dhania), turmeric (haldi). Beat the eggs with a pinch of turmeric and salt. Stir in finely chopped onion, tomato, green chili and cilantro. Heat a little oil in a pan, pour in the eggs and cook on medium until the bottom is set. Fold or flip and cook 30 seconds more.'),
  ('Anda Curry', 'Indian', 30, 3, ARRAY['eggs', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'turmeric (haldi)', 'red chili powder (lal mirch)', 'coriander powder (dhania)', 'garam masala', 'cilantro (hara dhania)'],
   'Hard-boil the eggs for 10 minutes, peel them and make a few shallow slits. Fry the onion until golden, then add ginger and garlic. Add the tomatoes, turmeric, chili powder, coriander powder and salt and cook until thick. Add a cup of water and the eggs and simmer 8 minutes. Finish with garam masala and cilantro.',
   false, true, true, true, true, true, 'starter', 'starter',
   'Anda Curry. Indian dish, 30 minutes. Ingredients: eggs, onion, tomatoes, ginger (adrak), garlic, turmeric (haldi), red chili powder (lal mirch), coriander powder (dhania), garam masala, cilantro (hara dhania). Hard-boil the eggs for 10 minutes, peel them and make a few shallow slits. Fry the onion until golden, then add ginger and garlic. Add the tomatoes, turmeric, chili powder, coriander powder and salt and cook until thick. Add a cup of water and the eggs and simmer 8 minutes. Finish with garam masala and cilantro.'),
  ('Homestyle Chicken Curry', 'Indian', 50, 4, ARRAY['chicken thighs', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'yogurt (dahi)', 'turmeric (haldi)', 'red chili powder (lal mirch)', 'coriander powder (dhania)', 'garam masala', 'cilantro (hara dhania)'],
   'Mix the chicken with yogurt, turmeric, chili powder and salt and set aside for 15 minutes. Fry the onion until deep golden, then add ginger and garlic. Add the tomatoes and coriander powder and cook until the oil separates. Add the chicken and cook on high for 5 minutes, then add a cup of water, cover and simmer 20 minutes until cooked through. Finish with garam masala and cilantro.',
   false, false, true, true, false, true, 'starter', 'starter',
   'Homestyle Chicken Curry. Indian dish, 50 minutes. Ingredients: chicken thighs, onion, tomatoes, ginger (adrak), garlic, yogurt (dahi), turmeric (haldi), red chili powder (lal mirch), coriander powder (dhania), garam masala, cilantro (hara dhania). Mix the chicken with yogurt, turmeric, chili powder and salt and set aside for 15 minutes. Fry the onion until deep golden, then add ginger and garlic. Add the tomatoes and coriander powder and cook until the oil separates. Add the chicken and cook on high for 5 minutes, then add a cup of water, cover and simmer 20 minutes until cooked through. Finish with garam masala and cilantro.'),
  ('Moong Dal Khichdi', 'Indian', 30, 3, ARRAY['moong dal', 'basmati rice', 'ghee', 'cumin seeds (jeera)', 'turmeric (haldi)', 'asafoetida (hing)', 'black pepper'],
   'Rinse the rice and moong dal together. Heat the ghee, crackle the cumin seeds and add the hing and a pinch of crushed black pepper. Add the rice and dal, turmeric, salt and 4 cups of water. Pressure-cook for 3 whistles, or simmer covered for 25 minutes, until soft and porridge-like. Serve with a spoon of ghee on top.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Moong Dal Khichdi. Indian dish, 30 minutes. Ingredients: moong dal, basmati rice, ghee, cumin seeds (jeera), turmeric (haldi), asafoetida (hing), black pepper. Rinse the rice and moong dal together. Heat the ghee, crackle the cumin seeds and add the hing and a pinch of crushed black pepper. Add the rice and dal, turmeric, salt and 4 cups of water. Pressure-cook for 3 whistles, or simmer covered for 25 minutes, until soft and porridge-like. Serve with a spoon of ghee on top.'),
  ('Bhindi Masala', 'Indian', 25, 3, ARRAY['okra (bhindi)', 'onion', 'tomatoes', 'cumin seeds (jeera)', 'turmeric (haldi)', 'red chili powder (lal mirch)', 'coriander powder (dhania)', 'amchur'],
   'Wash and fully dry the okra, then cut it into pieces. Fry it in oil on medium-high, uncovered, until it''s no longer sticky, and set it aside. Crackle the cumin seeds, fry the onion, then add the tomatoes and spices with salt. Return the okra, toss for 3 minutes and finish with amchur.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Bhindi Masala. Indian dish, 25 minutes. Ingredients: okra (bhindi), onion, tomatoes, cumin seeds (jeera), turmeric (haldi), red chili powder (lal mirch), coriander powder (dhania), amchur. Wash and fully dry the okra, then cut it into pieces. Fry it in oil on medium-high, uncovered, until it''s no longer sticky, and set it aside. Crackle the cumin seeds, fry the onion, then add the tomatoes and spices with salt. Return the okra, toss for 3 minutes and finish with amchur.'),
  ('Besan Chilla', 'Indian', 20, 2, ARRAY['besan (gram flour)', 'tomatoes', 'green chilies (hari mirch)', 'cilantro (hara dhania)', 'carom seeds (ajwain)', 'turmeric (haldi)'],
   'Whisk the besan with turmeric, ajwain, salt and enough water to make a pourable batter. Stir in finely chopped tomato, green chili and cilantro. Spread a ladle of batter thin on a hot oiled pan, cook until the edges lift, then flip and cook 1 minute more.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Besan Chilla. Indian dish, 20 minutes. Ingredients: besan (gram flour), tomatoes, green chilies (hari mirch), cilantro (hara dhania), carom seeds (ajwain), turmeric (haldi). Whisk the besan with turmeric, ajwain, salt and enough water to make a pourable batter. Stir in finely chopped tomato, green chili and cilantro. Spread a ladle of batter thin on a hot oiled pan, cook until the edges lift, then flip and cook 1 minute more.'),
  ('Lemon Rice', 'Indian', 20, 3, ARRAY['cooked rice', 'lemon', 'peanuts', 'mustard seeds (rai)', 'chana dal', 'urad dal', 'curry leaves (kadi patta)', 'green chilies (hari mirch)', 'turmeric (haldi)', 'asafoetida (hing)'],
   'Heat oil and fry the peanuts until crisp. Add the mustard seeds, chana dal and urad dal and fry until the dals turn golden. Add curry leaves, green chilies, hing and turmeric. Turn off the heat, add the cooked rice, lemon juice and salt, and mix gently.',
   true, true, true, false, true, false, 'starter', 'starter',
   'Lemon Rice. Indian dish, 20 minutes. Ingredients: cooked rice, lemon, peanuts, mustard seeds (rai), chana dal, urad dal, curry leaves (kadi patta), green chilies (hari mirch), turmeric (haldi), asafoetida (hing). Heat oil and fry the peanuts until crisp. Add the mustard seeds, chana dal and urad dal and fry until the dals turn golden. Add curry leaves, green chilies, hing and turmeric. Turn off the heat, add the cooked rice, lemon juice and salt, and mix gently.'),
  ('Curd Rice', 'Indian', 15, 2, ARRAY['cooked rice', 'yogurt (dahi)', 'milk', 'mustard seeds (rai)', 'curry leaves (kadi patta)', 'ginger (adrak)', 'green chilies (hari mirch)'],
   'Mash the rice lightly while it''s warm, then mix in the yogurt, a splash of milk and salt. Heat a little oil, crackle the mustard seeds and add curry leaves, grated ginger and green chilies. Pour this tempering over the rice and mix. Serve cool.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Curd Rice. Indian dish, 15 minutes. Ingredients: cooked rice, yogurt (dahi), milk, mustard seeds (rai), curry leaves (kadi patta), ginger (adrak), green chilies (hari mirch). Mash the rice lightly while it''s warm, then mix in the yogurt, a splash of milk and salt. Heat a little oil, crackle the mustard seeds and add curry leaves, grated ginger and green chilies. Pour this tempering over the rice and mix. Serve cool.'),
  ('Paneer Bhurji', 'Indian', 20, 2, ARRAY['paneer', 'onion', 'tomatoes', 'green chilies (hari mirch)', 'turmeric (haldi)', 'garam masala', 'butter', 'cilantro (hara dhania)'],
   'Melt the butter and fry the onion and green chilies until soft. Add the tomatoes, turmeric and salt and cook until mushy. Crumble in the paneer, add the garam masala and stir for 3 minutes. Finish with cilantro.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Paneer Bhurji. Indian dish, 20 minutes. Ingredients: paneer, onion, tomatoes, green chilies (hari mirch), turmeric (haldi), garam masala, butter, cilantro (hara dhania). Melt the butter and fry the onion and green chilies until soft. Add the tomatoes, turmeric and salt and cook until mushy. Crumble in the paneer, add the garam masala and stir for 3 minutes. Finish with cilantro.'),
  ('Masala Chai', 'Indian', 10, 2, ARRAY['black tea (chai patti)', 'milk', 'ginger (adrak)', 'cardamom (elaichi)', 'sugar'],
   'Bring 1 cup of water to a boil with crushed ginger and cardamom. Add the tea and simmer 2 minutes. Add 1 cup of milk and sugar to taste, bring back to a boil and simmer 2 minutes more. Strain into cups.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Masala Chai. Indian dish, 10 minutes. Ingredients: black tea (chai patti), milk, ginger (adrak), cardamom (elaichi), sugar. Bring 1 cup of water to a boil with crushed ginger and cardamom. Add the tea and simmer 2 minutes. Add 1 cup of milk and sugar to taste, bring back to a boil and simmer 2 minutes more. Strain into cups.'),
  ('Vegetable Pulao', 'Indian', 35, 4, ARRAY['basmati rice', 'frozen peas (matar)', 'carrots', 'green beans', 'onion', 'ghee', 'cumin seeds (jeera)', 'bay leaf (tej patta)', 'cloves (laung)', 'cardamom (elaichi)', 'cinnamon (dalchini)'],
   'Rinse and soak the rice for 15 minutes. Heat the ghee and fry the whole spices for 30 seconds, then the sliced onion until golden. Add the diced carrots, beans and peas and stir for 2 minutes. Add the drained rice, 1¾ cups of water per cup of rice and salt. Cover and cook on low for 12 minutes, then rest 5 minutes.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Vegetable Pulao. Indian dish, 35 minutes. Ingredients: basmati rice, frozen peas (matar), carrots, green beans, onion, ghee, cumin seeds (jeera), bay leaf (tej patta), cloves (laung), cardamom (elaichi), cinnamon (dalchini). Rinse and soak the rice for 15 minutes. Heat the ghee and fry the whole spices for 30 seconds, then the sliced onion until golden. Add the diced carrots, beans and peas and stir for 2 minutes. Add the drained rice, 1¾ cups of water per cup of rice and salt. Cover and cook on low for 12 minutes, then rest 5 minutes.'),
  ('Tamatar Paneer', 'Indian', 25, 3, ARRAY['paneer', 'tomatoes', 'cumin seeds (jeera)', 'asafoetida (hing)', 'turmeric (haldi)', 'red chili powder (lal mirch)', 'garam masala', 'fresh cream'],
   'Blend the tomatoes into a puree. Crackle the cumin seeds in oil, add the hing, then the puree, turmeric, chili powder and salt. Cook until thick and the oil separates. Add cubed paneer, garam masala and a spoon of cream and simmer 3 minutes.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Tamatar Paneer. Indian dish, 25 minutes. Ingredients: paneer, tomatoes, cumin seeds (jeera), asafoetida (hing), turmeric (haldi), red chili powder (lal mirch), garam masala, fresh cream. Blend the tomatoes into a puree. Crackle the cumin seeds in oil, add the hing, then the puree, turmeric, chili powder and salt. Cook until thick and the oil separates. Add cubed paneer, garam masala and a spoon of cream and simmer 3 minutes.'),
  ('Aloo Paratha', 'Indian', 40, 4, ARRAY['whole wheat flour (atta)', 'potatoes (aloo)', 'green chilies (hari mirch)', 'cilantro (hara dhania)', 'carom seeds (ajwain)', 'amchur', 'ghee'],
   'Knead the atta with water and a pinch of salt into a soft dough and rest it for 15 minutes. Boil and mash the potatoes, then mix in chopped green chilies, cilantro, ajwain, amchur and salt. Roll a ball of dough, fill it with the potato mix, seal and roll it out gently. Cook on a hot tawa, brushing with ghee, until golden spots appear on both sides.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Aloo Paratha. Indian dish, 40 minutes. Ingredients: whole wheat flour (atta), potatoes (aloo), green chilies (hari mirch), cilantro (hara dhania), carom seeds (ajwain), amchur, ghee. Knead the atta with water and a pinch of salt into a soft dough and rest it for 15 minutes. Boil and mash the potatoes, then mix in chopped green chilies, cilantro, ajwain, amchur and salt. Roll a ball of dough, fill it with the potato mix, seal and roll it out gently. Cook on a hot tawa, brushing with ghee, until golden spots appear on both sides.'),
  ('CCFA Tea', 'Indian', 10, 1, ARRAY['cumin seeds (jeera)', 'coriander seeds (dhania)', 'fennel seeds (saunf)', 'carom seeds (ajwain)', 'water'],
   'Add half a teaspoon each of cumin, coriander, fennel and ajwain seeds to 1½ cups of water. Simmer 5 to 7 minutes until it reduces to about a cup. Strain and sip warm.',
   true, true, true, true, true, true, 'starter', 'starter',
   'CCFA Tea. Indian dish, 10 minutes. Ingredients: cumin seeds (jeera), coriander seeds (dhania), fennel seeds (saunf), carom seeds (ajwain), water. Add half a teaspoon each of cumin, coriander, fennel and ajwain seeds to 1½ cups of water. Simmer 5 to 7 minutes until it reduces to about a cup. Strain and sip warm.'),
  ('Soaked Walnuts and Black Raisins', 'Indian', 5, 1, ARRAY['walnuts (akhrot)', 'black raisins'],
   'Soak 3 walnut halves and 5 black raisins in water overnight. Drain and eat first thing in the morning.',
   true, true, true, true, true, false, 'starter', 'starter',
   'Soaked Walnuts and Black Raisins. Indian dish, 5 minutes. Ingredients: walnuts (akhrot), black raisins. Soak 3 walnut halves and 5 black raisins in water overnight. Drain and eat first thing in the morning.'),
  ('Soaked Almonds', 'Indian', 5, 1, ARRAY['almonds (badam)'],
   'Soak 5 almonds in water overnight. Peel if you like and eat in the morning.',
   true, true, true, true, true, false, 'starter', 'starter',
   'Soaked Almonds. Indian dish, 5 minutes. Ingredients: almonds (badam). Soak 5 almonds in water overnight. Peel if you like and eat in the morning.'),
  ('Soaked Brazil Nut, Fig and Methi Seeds', 'Indian', 5, 1, ARRAY['brazil nuts', 'dried figs (anjeer)', 'fenugreek seeds (methi)'],
   'Soak 1 Brazil nut, 1 dried fig and a spoon of methi seeds overnight in a little water. Eat in the morning; you can drink the methi water too.',
   true, true, true, true, true, false, 'starter', 'starter',
   'Soaked Brazil Nut, Fig and Methi Seeds. Indian dish, 5 minutes. Ingredients: brazil nuts, dried figs (anjeer), fenugreek seeds (methi). Soak 1 Brazil nut, 1 dried fig and a spoon of methi seeds overnight in a little water. Eat in the morning; you can drink the methi water too.'),
  ('Ragi Ganji', 'South Indian', 10, 1, ARRAY['ragi flour', 'water', 'buttermilk', 'salt'],
   'Whisk 2 tablespoons of ragi flour into 1 cup of cold water until smooth. Cook on low, stirring, for 5 to 6 minutes until it thickens and turns glossy. Cool slightly, then stir in buttermilk and a pinch of salt.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Ragi Ganji. South Indian dish, 10 minutes. Ingredients: ragi flour, water, buttermilk, salt. Whisk 2 tablespoons of ragi flour into 1 cup of cold water until smooth. Cook on low, stirring, for 5 to 6 minutes until it thickens and turns glossy. Cool slightly, then stir in buttermilk and a pinch of salt.'),
  ('Almond Milk Tea', 'Indian', 10, 1, ARRAY['black tea (chai patti)', 'almond milk', 'cardamom (elaichi)'],
   'Simmer the tea and a crushed cardamom pod in half a cup of water for 2 minutes. Add half a cup of almond milk and heat until just steaming, without boiling hard. Strain.',
   true, true, true, true, true, false, 'starter', 'starter',
   'Almond Milk Tea. Indian dish, 10 minutes. Ingredients: black tea (chai patti), almond milk, cardamom (elaichi). Simmer the tea and a crushed cardamom pod in half a cup of water for 2 minutes. Add half a cup of almond milk and heat until just steaming, without boiling hard. Strain.'),
  ('Spearmint Tea', 'Global', 5, 1, ARRAY['spearmint leaves', 'water'],
   'Pour just-boiled water over a small handful of spearmint leaves or a teabag. Steep 5 minutes and strain.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Spearmint Tea. Global dish, 5 minutes. Ingredients: spearmint leaves, water. Pour just-boiled water over a small handful of spearmint leaves or a teabag. Steep 5 minutes and strain.'),
  ('Mushroom Spinach Omelette', 'Indian', 15, 1, ARRAY['eggs', 'mushrooms', 'spinach (palak)', 'black pepper', 'salt'],
   'Sauté sliced mushrooms in a little oil until browned, then add the spinach until it wilts. Pour in 3 beaten eggs seasoned with salt and pepper. Cook on medium until set, then fold.',
   false, true, true, true, true, true, 'starter', 'starter',
   'Mushroom Spinach Omelette. Indian dish, 15 minutes. Ingredients: eggs, mushrooms, spinach (palak), black pepper, salt. Sauté sliced mushrooms in a little oil until browned, then add the spinach until it wilts. Pour in 3 beaten eggs seasoned with salt and pepper. Cook on medium until set, then fold.'),
  ('Spinach Besan Chilla', 'Indian', 20, 2, ARRAY['besan (gram flour)', 'spinach (palak)', 'green chilies (hari mirch)', 'carom seeds (ajwain)', 'turmeric (haldi)'],
   'Whisk the besan with turmeric, ajwain, salt and water into a pourable batter. Stir in finely chopped spinach and green chili. Spread thin on a hot oiled pan, cook until the edges lift, flip and cook 1 minute more. Serve with coriander mint chutney.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Spinach Besan Chilla. Indian dish, 20 minutes. Ingredients: besan (gram flour), spinach (palak), green chilies (hari mirch), carom seeds (ajwain), turmeric (haldi). Whisk the besan with turmeric, ajwain, salt and water into a pourable batter. Stir in finely chopped spinach and green chili. Spread thin on a hot oiled pan, cook until the edges lift, flip and cook 1 minute more. Serve with coriander mint chutney.'),
  ('Coriander Mint Chutney', 'Indian', 10, 4, ARRAY['cilantro (hara dhania)', 'mint leaves (pudina)', 'green chilies (hari mirch)', 'lemon', 'cumin seeds (jeera)', 'salt'],
   'Blend a big handful of cilantro, half as much mint, 1 or 2 green chilies, a pinch of cumin, lemon juice, salt and a splash of cold water until smooth. Keeps 3 days in the fridge.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Coriander Mint Chutney. Indian dish, 10 minutes. Ingredients: cilantro (hara dhania), mint leaves (pudina), green chilies (hari mirch), lemon, cumin seeds (jeera), salt. Blend a big handful of cilantro, half as much mint, 1 or 2 green chilies, a pinch of cumin, lemon juice, salt and a splash of cold water until smooth. Keeps 3 days in the fridge.'),
  ('Coconut Chutney', 'South Indian', 10, 4, ARRAY['grated coconut (nariyal)', 'roasted chana', 'green chilies (hari mirch)', 'mustard seeds (rai)', 'curry leaves (kadi patta)', 'salt'],
   'Blend the coconut, roasted chana, green chili and salt with a little water until smooth. Crackle mustard seeds and curry leaves in a spoon of oil and pour over the chutney.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Coconut Chutney. South Indian dish, 10 minutes. Ingredients: grated coconut (nariyal), roasted chana, green chilies (hari mirch), mustard seeds (rai), curry leaves (kadi patta), salt. Blend the coconut, roasted chana, green chili and salt with a little water until smooth. Crackle mustard seeds and curry leaves in a spoon of oil and pour over the chutney.'),
  ('Yogurt Chia Pudding with Berries', 'Global', 5, 1, ARRAY['yogurt (dahi)', 'chia seeds', 'berries'],
   'Stir 2 tablespoons of chia seeds into 200 g of yogurt. Chill at least 2 hours or overnight, then top with berries.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Yogurt Chia Pudding with Berries. Global dish, 5 minutes. Ingredients: yogurt (dahi), chia seeds, berries. Stir 2 tablespoons of chia seeds into 200 g of yogurt. Chill at least 2 hours or overnight, then top with berries.'),
  ('Yellow Moong Dal Egg Chilla', 'Indian', 25, 2, ARRAY['yellow moong dal', 'eggs', 'green chilies (hari mirch)', 'ginger (adrak)', 'cilantro (hara dhania)', 'cumin seeds (jeera)'],
   'Soak the moong dal for 3 hours, then grind it with ginger, green chili, cumin and salt into a smooth batter. Spread a ladle thin on a hot pan, crack an egg over it and spread it out. Cook until set, flip briefly and finish with cilantro.',
   false, true, true, true, true, true, 'starter', 'starter',
   'Yellow Moong Dal Egg Chilla. Indian dish, 25 minutes. Ingredients: yellow moong dal, eggs, green chilies (hari mirch), ginger (adrak), cilantro (hara dhania), cumin seeds (jeera). Soak the moong dal for 3 hours, then grind it with ginger, green chili, cumin and salt into a smooth batter. Spread a ladle thin on a hot pan, crack an egg over it and spread it out. Cook until set, flip briefly and finish with cilantro.'),
  ('Sourdough Toast with Guacamole and Spinach Scrambled Eggs', 'Global', 15, 1, ARRAY['sourdough bread', 'avocado', 'lemon', 'eggs', 'spinach (palak)', 'black pepper'],
   'Mash the avocado with lemon juice, salt and pepper. Wilt the spinach in a pan, add the beaten eggs and stir gently until softly set. Toast the sourdough, spread the guacamole and top with the eggs.',
   false, true, true, false, true, true, 'starter', 'starter',
   'Sourdough Toast with Guacamole and Spinach Scrambled Eggs. Global dish, 15 minutes. Ingredients: sourdough bread, avocado, lemon, eggs, spinach (palak), black pepper. Mash the avocado with lemon juice, salt and pepper. Wilt the spinach in a pan, add the beaten eggs and stir gently until softly set. Toast the sourdough, spread the guacamole and top with the eggs.'),
  ('Sourdough Toast with Hummus and Eggs', 'Global', 15, 1, ARRAY['sourdough bread', 'hummus', 'eggs', 'black pepper'],
   'Toast the sourdough and spread it thickly with hummus. Top with 2 eggs, fried or scrambled, and a crack of black pepper.',
   false, true, true, false, true, true, 'starter', 'starter',
   'Sourdough Toast with Hummus and Eggs. Global dish, 15 minutes. Ingredients: sourdough bread, hummus, eggs, black pepper. Toast the sourdough and spread it thickly with hummus. Top with 2 eggs, fried or scrambled, and a crack of black pepper.'),
  ('Ragi Moong Dal Idli', 'South Indian', 30, 3, ARRAY['ragi flour', 'yellow moong dal', 'yogurt (dahi)', 'fruit salt (eno)', 'salt'],
   'Soak the moong dal for 3 hours and grind it smooth. Mix with ragi flour, yogurt, salt and enough water for a thick batter, and rest 15 minutes. Stir in the fruit salt, fill greased idli plates and steam 12 minutes. Serve with coconut or peanut chutney.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Ragi Moong Dal Idli. South Indian dish, 30 minutes. Ingredients: ragi flour, yellow moong dal, yogurt (dahi), fruit salt (eno), salt. Soak the moong dal for 3 hours and grind it smooth. Mix with ragi flour, yogurt, salt and enough water for a thick batter, and rest 15 minutes. Stir in the fruit salt, fill greased idli plates and steam 12 minutes. Serve with coconut or peanut chutney.'),
  ('Mixed Dal Idli', 'South Indian', 30, 3, ARRAY['yellow moong dal', 'chana dal', 'urad dal', 'ginger (adrak)', 'green chilies (hari mirch)', 'fruit salt (eno)', 'salt'],
   'Soak the three dals together for 4 hours, then grind them with ginger, green chili and salt into a thick batter. Stir in the fruit salt, fill greased idli plates and steam 12 to 15 minutes.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Mixed Dal Idli. South Indian dish, 30 minutes. Ingredients: yellow moong dal, chana dal, urad dal, ginger (adrak), green chilies (hari mirch), fruit salt (eno), salt. Soak the three dals together for 4 hours, then grind them with ginger, green chili and salt into a thick batter. Stir in the fruit salt, fill greased idli plates and steam 12 to 15 minutes.'),
  ('Egg Pesarattu', 'South Indian', 25, 2, ARRAY['green moong', 'ginger (adrak)', 'green chilies (hari mirch)', 'cumin seeds (jeera)', 'eggs', 'salt'],
   'Soak whole green moong overnight, then grind it with ginger, green chili, cumin and salt into a batter. Spread a ladle thin on a hot pan, crack an egg on top and spread it over. Drizzle oil, cook until crisp underneath, and fold. Serve with coconut or tomato chutney.',
   false, true, true, true, true, true, 'starter', 'starter',
   'Egg Pesarattu. South Indian dish, 25 minutes. Ingredients: green moong, ginger (adrak), green chilies (hari mirch), cumin seeds (jeera), eggs, salt. Soak whole green moong overnight, then grind it with ginger, green chili, cumin and salt into a batter. Spread a ladle thin on a hot pan, crack an egg on top and spread it over. Drizzle oil, cook until crisp underneath, and fold. Serve with coconut or tomato chutney.'),
  ('Moong Dal Dosa', 'South Indian', 25, 2, ARRAY['yellow moong dal', 'ginger (adrak)', 'green chilies (hari mirch)', 'cumin seeds (jeera)', 'salt'],
   'Soak the moong dal for 3 hours and grind it with ginger, green chili, cumin and salt into a smooth batter. Spread thin on a hot pan, drizzle a little oil and cook until golden. Serve with mint chutney.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Moong Dal Dosa. South Indian dish, 25 minutes. Ingredients: yellow moong dal, ginger (adrak), green chilies (hari mirch), cumin seeds (jeera), salt. Soak the moong dal for 3 hours and grind it with ginger, green chili, cumin and salt into a smooth batter. Spread thin on a hot pan, drizzle a little oil and cook until golden. Serve with mint chutney.'),
  ('Quinoa Egg Dosa', 'South Indian', 25, 2, ARRAY['quinoa', 'urad dal', 'eggs', 'salt'],
   'Soak the quinoa and urad dal for 4 hours and grind into a smooth batter with salt. Spread a ladle on a hot pan, crack an egg over it and spread. Cook until set and golden underneath, then fold.',
   false, true, true, true, true, true, 'starter', 'starter',
   'Quinoa Egg Dosa. South Indian dish, 25 minutes. Ingredients: quinoa, urad dal, eggs, salt. Soak the quinoa and urad dal for 4 hours and grind into a smooth batter with salt. Spread a ladle on a hot pan, crack an egg over it and spread. Cook until set and golden underneath, then fold.'),
  ('Ragi Oats Dosa with Paneer', 'South Indian', 20, 2, ARRAY['ragi flour', 'oats', 'yogurt (dahi)', 'paneer', 'green chilies (hari mirch)', 'cilantro (hara dhania)', 'salt'],
   'Grind the oats to a powder, mix with ragi flour, yogurt, salt and water into a pourable batter, and rest 10 minutes. Spread on a hot pan, sprinkle with grated paneer, green chili and cilantro, and cook until crisp.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Ragi Oats Dosa with Paneer. South Indian dish, 20 minutes. Ingredients: ragi flour, oats, yogurt (dahi), paneer, green chilies (hari mirch), cilantro (hara dhania), salt. Grind the oats to a powder, mix with ragi flour, yogurt, salt and water into a pourable batter, and rest 10 minutes. Spread on a hot pan, sprinkle with grated paneer, green chili and cilantro, and cook until crisp.'),
  ('Overnight Soaked Oats', 'Global', 5, 1, ARRAY['rolled oats', 'milk', 'chia seeds', 'black raisins', 'berries'],
   'Mix 40 g of oats with 200 ml of milk or yogurt, a tablespoon of chia seeds and 5 black raisins. Refrigerate overnight and top with berries in the morning.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Overnight Soaked Oats. Global dish, 5 minutes. Ingredients: rolled oats, milk, chia seeds, black raisins, berries. Mix 40 g of oats with 200 ml of milk or yogurt, a tablespoon of chia seeds and 5 black raisins. Refrigerate overnight and top with berries in the morning.'),
  ('High-Protein Cocoa Oatmeal', 'Global', 10, 1, ARRAY['rolled oats', 'milk', 'chia seeds', 'cocoa powder', 'black raisins', 'peanut butter'],
   'Simmer 40 g of oats in 200 ml of milk for 4 minutes, stirring. Stir in the chia seeds and half a spoon of cocoa, then top with raisins and a spoon of peanut butter.',
   true, true, true, false, false, false, 'starter', 'starter',
   'High-Protein Cocoa Oatmeal. Global dish, 10 minutes. Ingredients: rolled oats, milk, chia seeds, cocoa powder, black raisins, peanut butter. Simmer 40 g of oats in 200 ml of milk for 4 minutes, stirring. Stir in the chia seeds and half a spoon of cocoa, then top with raisins and a spoon of peanut butter.'),
  ('Vegetable Upma', 'South Indian', 25, 2, ARRAY['semolina (rava)', 'onion', 'carrots', 'green beans', 'peas (matar)', 'mustard seeds (rai)', 'curry leaves (kadi patta)', 'green chilies (hari mirch)'],
   'Dry-roast the semolina and set it aside. Crackle the mustard seeds with curry leaves and green chili, then soften the onion. Add the diced carrots, beans and peas with salt and cook 3 minutes. Pour in 2½ cups of water, bring to a boil and stream in the semolina while stirring. Cover and cook 3 minutes.',
   true, true, true, false, true, true, 'starter', 'starter',
   'Vegetable Upma. South Indian dish, 25 minutes. Ingredients: semolina (rava), onion, carrots, green beans, peas (matar), mustard seeds (rai), curry leaves (kadi patta), green chilies (hari mirch). Dry-roast the semolina and set it aside. Crackle the mustard seeds with curry leaves and green chili, then soften the onion. Add the diced carrots, beans and peas with salt and cook 3 minutes. Pour in 2½ cups of water, bring to a boil and stream in the semolina while stirring. Cover and cook 3 minutes.'),
  ('Broken Wheat Vegetable Upma', 'Indian', 30, 2, ARRAY['broken wheat (dalia)', 'onion', 'carrots', 'green beans', 'peas (matar)', 'mustard seeds (rai)', 'curry leaves (kadi patta)', 'green chilies (hari mirch)'],
   'Roast the broken wheat in a dry pan until fragrant. Crackle mustard seeds and curry leaves, soften the onion and green chili, then add the vegetables. Add the wheat, 2½ cups of water and salt, cover and cook on low 15 minutes until tender.',
   true, true, true, false, true, true, 'starter', 'starter',
   'Broken Wheat Vegetable Upma. Indian dish, 30 minutes. Ingredients: broken wheat (dalia), onion, carrots, green beans, peas (matar), mustard seeds (rai), curry leaves (kadi patta), green chilies (hari mirch). Roast the broken wheat in a dry pan until fragrant. Crackle mustard seeds and curry leaves, soften the onion and green chili, then add the vegetables. Add the wheat, 2½ cups of water and salt, cover and cook on low 15 minutes until tender.'),
  ('Vegetable Poha', 'Indian', 20, 2, ARRAY['poha', 'onion', 'green beans', 'peas (matar)', 'carrots', 'mustard seeds (rai)', 'curry leaves (kadi patta)', 'turmeric (haldi)', 'lemon'],
   'Rinse the poha and let it soften 5 minutes. Crackle the mustard seeds with curry leaves, add the onion, then the finely chopped beans, carrots and peas with a splash of water; cover until tender. Add turmeric, salt and the poha, toss gently and finish with lemon juice.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Vegetable Poha. Indian dish, 20 minutes. Ingredients: poha, onion, green beans, peas (matar), carrots, mustard seeds (rai), curry leaves (kadi patta), turmeric (haldi), lemon. Rinse the poha and let it soften 5 minutes. Crackle the mustard seeds with curry leaves, add the onion, then the finely chopped beans, carrots and peas with a splash of water; cover until tender. Add turmeric, salt and the poha, toss gently and finish with lemon juice.'),
  ('Chickpea Pomegranate Salad', 'Indian', 10, 1, ARRAY['canned chickpeas', 'pomegranate (anar)', 'cucumber', 'lemon', 'cilantro (hara dhania)', 'chaat masala'],
   'Toss 60 g of drained chickpeas with half a pomegranate''s seeds, diced cucumber, cilantro, lemon juice, chaat masala and salt.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Chickpea Pomegranate Salad. Indian dish, 10 minutes. Ingredients: canned chickpeas, pomegranate (anar), cucumber, lemon, cilantro (hara dhania), chaat masala. Toss 60 g of drained chickpeas with half a pomegranate''s seeds, diced cucumber, cilantro, lemon juice, chaat masala and salt.'),
  ('Mixed Pulses Chaat', 'Indian', 15, 2, ARRAY['cowpeas (lobia)', 'kala chana', 'green moong', 'onion', 'tomatoes', 'lemon', 'chaat masala', 'cilantro (hara dhania)'],
   'Soak the cowpeas, kala chana and green moong overnight, then pressure-cook until just tender. Toss with chopped onion, tomato, cilantro, lemon juice, chaat masala and salt.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Mixed Pulses Chaat. Indian dish, 15 minutes. Ingredients: cowpeas (lobia), kala chana, green moong, onion, tomatoes, lemon, chaat masala, cilantro (hara dhania). Soak the cowpeas, kala chana and green moong overnight, then pressure-cook until just tender. Toss with chopped onion, tomato, cilantro, lemon juice, chaat masala and salt.'),
  ('Tofu Curry', 'Indian', 30, 3, ARRAY['tofu', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'turmeric (haldi)', 'coriander powder (dhania)', 'garam masala'],
   'Press and cube the tofu, then sear until golden. Fry the onion, add ginger and garlic, then the tomatoes and spices with salt and cook into a thick masala. Add a cup of water and the tofu and simmer 8 minutes.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Tofu Curry. Indian dish, 30 minutes. Ingredients: tofu, onion, tomatoes, ginger (adrak), garlic, turmeric (haldi), coriander powder (dhania), garam masala. Press and cube the tofu, then sear until golden. Fry the onion, add ginger and garlic, then the tomatoes and spices with salt and cook into a thick masala. Add a cup of water and the tofu and simmer 8 minutes.'),
  ('Tofu Bhurji', 'Indian', 15, 2, ARRAY['tofu', 'onion', 'tomatoes', 'green chilies (hari mirch)', 'turmeric (haldi)', 'cilantro (hara dhania)'],
   'Soften the onion and green chili in oil, add the tomatoes, turmeric and salt and cook until soft. Crumble in the tofu and stir for 4 minutes. Finish with cilantro.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Tofu Bhurji. Indian dish, 15 minutes. Ingredients: tofu, onion, tomatoes, green chilies (hari mirch), turmeric (haldi), cilantro (hara dhania). Soften the onion and green chili in oil, add the tomatoes, turmeric and salt and cook until soft. Crumble in the tofu and stir for 4 minutes. Finish with cilantro.'),
  ('Spinach Methi Dal', 'Indian', 30, 3, ARRAY['toor dal (arhar)', 'spinach (palak)', 'fenugreek leaves (methi)', 'tomatoes', 'garlic', 'cumin seeds (jeera)', 'turmeric (haldi)'],
   'Pressure-cook the dal with turmeric and salt until soft. Crackle cumin and garlic in oil, add the tomatoes, then the chopped spinach and methi until wilted. Stir in the dal with some water and simmer 5 minutes.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Spinach Methi Dal. Indian dish, 30 minutes. Ingredients: toor dal (arhar), spinach (palak), fenugreek leaves (methi), tomatoes, garlic, cumin seeds (jeera), turmeric (haldi). Pressure-cook the dal with turmeric and salt until soft. Crackle cumin and garlic in oil, add the tomatoes, then the chopped spinach and methi until wilted. Stir in the dal with some water and simmer 5 minutes.'),
  ('Tomato Drumstick Curry', 'South Indian', 30, 3, ARRAY['drumsticks', 'tomatoes', 'onion', 'mustard seeds (rai)', 'curry leaves (kadi patta)', 'turmeric (haldi)', 'red chili powder (lal mirch)', 'coriander powder (dhania)'],
   'Cut the drumsticks into finger lengths. Crackle mustard seeds and curry leaves, fry the onion, then add the tomatoes and spices with salt. Add the drumsticks and a cup of water, cover and simmer 15 minutes until tender.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Tomato Drumstick Curry. South Indian dish, 30 minutes. Ingredients: drumsticks, tomatoes, onion, mustard seeds (rai), curry leaves (kadi patta), turmeric (haldi), red chili powder (lal mirch), coriander powder (dhania). Cut the drumsticks into finger lengths. Crackle mustard seeds and curry leaves, fry the onion, then add the tomatoes and spices with salt. Add the drumsticks and a cup of water, cover and simmer 15 minutes until tender.'),
  ('Drumstick Dal', 'South Indian', 35, 4, ARRAY['toor dal (arhar)', 'drumsticks', 'tomatoes', 'tamarind (imli)', 'mustard seeds (rai)', 'curry leaves (kadi patta)', 'turmeric (haldi)', 'sambar powder'],
   'Pressure-cook the dal with turmeric. Simmer the drumstick pieces with tomatoes, tamarind water, sambar powder and salt until tender. Add the dal and simmer 5 minutes, then pour over a tempering of mustard seeds and curry leaves.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Drumstick Dal. South Indian dish, 35 minutes. Ingredients: toor dal (arhar), drumsticks, tomatoes, tamarind (imli), mustard seeds (rai), curry leaves (kadi patta), turmeric (haldi), sambar powder. Pressure-cook the dal with turmeric. Simmer the drumstick pieces with tomatoes, tamarind water, sambar powder and salt until tender. Add the dal and simmer 5 minutes, then pour over a tempering of mustard seeds and curry leaves.'),
  ('Drumstick Egg Curry', 'South Indian', 35, 3, ARRAY['drumsticks', 'eggs', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'turmeric (haldi)', 'red chili powder (lal mirch)', 'coriander powder (dhania)'],
   'Hard-boil and peel 2 eggs. Fry the onion, add ginger and garlic, then the tomatoes and spices. Add the drumstick pieces with a cup of water and simmer 12 minutes, then add the eggs and simmer 5 more.',
   false, true, true, true, true, true, 'starter', 'starter',
   'Drumstick Egg Curry. South Indian dish, 35 minutes. Ingredients: drumsticks, eggs, onion, tomatoes, ginger (adrak), garlic, turmeric (haldi), red chili powder (lal mirch), coriander powder (dhania). Hard-boil and peel 2 eggs. Fry the onion, add ginger and garlic, then the tomatoes and spices. Add the drumstick pieces with a cup of water and simmer 12 minutes, then add the eggs and simmer 5 more.'),
  ('Drumstick Soup', 'South Indian', 30, 2, ARRAY['drumsticks', 'tomatoes', 'garlic', 'black pepper', 'cumin seeds (jeera)'],
   'Simmer the drumstick pieces with a tomato and garlic in 3 cups of water for 20 minutes. Scrape the pulp from the drumsticks, blend it with the tomato and strain. Season with pepper, roasted cumin and salt.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Drumstick Soup. South Indian dish, 30 minutes. Ingredients: drumsticks, tomatoes, garlic, black pepper, cumin seeds (jeera). Simmer the drumstick pieces with a tomato and garlic in 3 cups of water for 20 minutes. Scrape the pulp from the drumsticks, blend it with the tomato and strain. Season with pepper, roasted cumin and salt.'),
  ('Air-Fried Chicken', 'Indian', 30, 2, ARRAY['chicken breast', 'yogurt (dahi)', 'ginger (adrak)', 'garlic', 'red chili powder (lal mirch)', 'turmeric (haldi)', 'garam masala', 'lemon'],
   'Marinate bite-sized chicken in yogurt, ginger, garlic, spices, lemon and salt for at least 20 minutes. Air-fry at 200°C (400°F) for 14 to 16 minutes, shaking halfway, until cooked through.',
   false, false, true, true, false, true, 'starter', 'starter',
   'Air-Fried Chicken. Indian dish, 30 minutes. Ingredients: chicken breast, yogurt (dahi), ginger (adrak), garlic, red chili powder (lal mirch), turmeric (haldi), garam masala, lemon. Marinate bite-sized chicken in yogurt, ginger, garlic, spices, lemon and salt for at least 20 minutes. Air-fry at 200°C (400°F) for 14 to 16 minutes, shaking halfway, until cooked through.'),
  ('Methi Chicken', 'Indian', 40, 3, ARRAY['chicken breast', 'fenugreek leaves (methi)', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'yogurt (dahi)', 'garam masala'],
   'Fry the onion until golden, then add ginger and garlic, the tomatoes and salt. Add the chicken and cook 5 minutes, then the whisked yogurt and garam masala. Cover and simmer 15 minutes. Stir in the chopped methi and cook 5 minutes more.',
   false, false, true, true, false, true, 'starter', 'starter',
   'Methi Chicken. Indian dish, 40 minutes. Ingredients: chicken breast, fenugreek leaves (methi), onion, tomatoes, ginger (adrak), garlic, yogurt (dahi), garam masala. Fry the onion until golden, then add ginger and garlic, the tomatoes and salt. Add the chicken and cook 5 minutes, then the whisked yogurt and garam masala. Cover and simmer 15 minutes. Stir in the chopped methi and cook 5 minutes more.'),
  ('Gongura Chicken Pulao', 'South Indian', 45, 3, ARRAY['chicken breast', 'brown rice', 'gongura', 'onion', 'ginger (adrak)', 'garlic', 'green chilies (hari mirch)', 'garam masala'],
   'Cook the gongura leaves with a little salt until they collapse into a tangy paste. Fry the onion, ginger, garlic and green chilies, add the chicken and brown it, then the gongura and garam masala. Add the soaked brown rice and 2½ cups of water and cook covered until the rice is tender.',
   false, false, true, true, true, true, 'starter', 'starter',
   'Gongura Chicken Pulao. South Indian dish, 45 minutes. Ingredients: chicken breast, brown rice, gongura, onion, ginger (adrak), garlic, green chilies (hari mirch), garam masala. Cook the gongura leaves with a little salt until they collapse into a tangy paste. Fry the onion, ginger, garlic and green chilies, add the chicken and brown it, then the gongura and garam masala. Add the soaked brown rice and 2½ cups of water and cook covered until the rice is tender.'),
  ('Chicken Pulao', 'Indian', 45, 3, ARRAY['chicken breast', 'brown rice', 'onion', 'yogurt (dahi)', 'ginger (adrak)', 'garlic', 'bay leaf (tej patta)', 'garam masala'],
   'Fry the bay leaf and onion until golden, add ginger and garlic, then the chicken and yogurt, and cook 5 minutes. Add the soaked brown rice, garam masala, salt and 2½ cups of water. Cover and cook on low until the rice is tender.',
   false, false, true, true, false, true, 'starter', 'starter',
   'Chicken Pulao. Indian dish, 45 minutes. Ingredients: chicken breast, brown rice, onion, yogurt (dahi), ginger (adrak), garlic, bay leaf (tej patta), garam masala. Fry the bay leaf and onion until golden, add ginger and garlic, then the chicken and yogurt, and cook 5 minutes. Add the soaked brown rice, garam masala, salt and 2½ cups of water. Cover and cook on low until the rice is tender.'),
  ('Broccoli Almond Soup', 'Global', 25, 2, ARRAY['broccoli', 'almonds (badam)', 'onion', 'garlic', 'black pepper'],
   'Soften the onion and garlic in a little oil. Add the broccoli, a handful of almonds and 3 cups of water with salt, and simmer 12 minutes. Blend smooth and season with pepper.',
   true, true, true, true, true, false, 'starter', 'starter',
   'Broccoli Almond Soup. Global dish, 25 minutes. Ingredients: broccoli, almonds (badam), onion, garlic, black pepper. Soften the onion and garlic in a little oil. Add the broccoli, a handful of almonds and 3 cups of water with salt, and simmer 12 minutes. Blend smooth and season with pepper.'),
  ('Pumpkin Soup', 'Global', 30, 2, ARRAY['pumpkin (kaddu)', 'onion', 'garlic', 'black pepper', 'cumin seeds (jeera)'],
   'Soften the onion and garlic, add the cubed pumpkin and 3 cups of water with salt, and simmer 15 minutes. Blend smooth and season with pepper and roasted cumin.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Pumpkin Soup. Global dish, 30 minutes. Ingredients: pumpkin (kaddu), onion, garlic, black pepper, cumin seeds (jeera). Soften the onion and garlic, add the cubed pumpkin and 3 cups of water with salt, and simmer 15 minutes. Blend smooth and season with pepper and roasted cumin.'),
  ('Ragi Tofu Soup', 'Indian', 20, 2, ARRAY['ragi flour', 'tofu', 'mixed vegetables', 'garlic', 'black pepper'],
   'Simmer finely chopped vegetables and garlic in 3 cups of water for 8 minutes. Whisk 2 tablespoons of ragi flour with cold water, stir it in and cook until it thickens. Add cubed tofu, salt and pepper and heat through.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Ragi Tofu Soup. Indian dish, 20 minutes. Ingredients: ragi flour, tofu, mixed vegetables, garlic, black pepper. Simmer finely chopped vegetables and garlic in 3 cups of water for 8 minutes. Whisk 2 tablespoons of ragi flour with cold water, stir it in and cook until it thickens. Add cubed tofu, salt and pepper and heat through.'),
  ('Spinach Soup', 'Global', 20, 2, ARRAY['spinach (palak)', 'onion', 'garlic', 'black pepper'],
   'Soften the onion and garlic, add the spinach and 2 cups of water and simmer 5 minutes. Blend smooth and season with salt and pepper.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Spinach Soup. Global dish, 20 minutes. Ingredients: spinach (palak), onion, garlic, black pepper. Soften the onion and garlic, add the spinach and 2 cups of water and simmer 5 minutes. Blend smooth and season with salt and pepper.'),
  ('Soya Chunks Pulao', 'Indian', 35, 3, ARRAY['soya chunks', 'brown rice', 'onion', 'peas (matar)', 'carrots', 'cumin seeds (jeera)', 'bay leaf (tej patta)', 'garam masala'],
   'Soak the soya chunks in hot water for 10 minutes and squeeze dry. Fry the cumin and bay leaf, then the onion, vegetables and soya. Add the soaked brown rice, garam masala, salt and water, cover and cook until tender.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Soya Chunks Pulao. Indian dish, 35 minutes. Ingredients: soya chunks, brown rice, onion, peas (matar), carrots, cumin seeds (jeera), bay leaf (tej patta), garam masala. Soak the soya chunks in hot water for 10 minutes and squeeze dry. Fry the cumin and bay leaf, then the onion, vegetables and soya. Add the soaked brown rice, garam masala, salt and water, cover and cook until tender.'),
  ('Soya Chunks Curry', 'Indian', 30, 3, ARRAY['soya chunks', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'turmeric (haldi)', 'coriander powder (dhania)', 'garam masala'],
   'Soak the soya chunks in hot water and squeeze dry. Fry the onion, then ginger, garlic, tomatoes and spices into a masala. Add the soya and a cup of water and simmer 10 minutes.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Soya Chunks Curry. Indian dish, 30 minutes. Ingredients: soya chunks, onion, tomatoes, ginger (adrak), garlic, turmeric (haldi), coriander powder (dhania), garam masala. Soak the soya chunks in hot water and squeeze dry. Fry the onion, then ginger, garlic, tomatoes and spices into a masala. Add the soya and a cup of water and simmer 10 minutes.'),
  ('Paneer Chickpeas Pulao', 'Indian', 35, 3, ARRAY['paneer', 'canned chickpeas', 'brown rice', 'onion', 'cumin seeds (jeera)', 'bay leaf (tej patta)', 'garam masala'],
   'Fry the cumin and bay leaf, then the onion until golden. Add the soaked brown rice, drained chickpeas, garam masala, salt and water, and cook covered until tender. Fold in cubes of lightly seared paneer.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Paneer Chickpeas Pulao. Indian dish, 35 minutes. Ingredients: paneer, canned chickpeas, brown rice, onion, cumin seeds (jeera), bay leaf (tej patta), garam masala. Fry the cumin and bay leaf, then the onion until golden. Add the soaked brown rice, drained chickpeas, garam masala, salt and water, and cook covered until tender. Fold in cubes of lightly seared paneer.'),
  ('Sprouts Curry', 'Indian', 25, 3, ARRAY['moong sprouts', 'onion', 'tomatoes', 'ginger (adrak)', 'turmeric (haldi)', 'coriander powder (dhania)', 'garam masala'],
   'Fry the onion and ginger, add the tomatoes and spices with salt and cook until soft. Add the sprouts and half a cup of water, cover and cook 8 minutes until just tender.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Sprouts Curry. Indian dish, 25 minutes. Ingredients: moong sprouts, onion, tomatoes, ginger (adrak), turmeric (haldi), coriander powder (dhania), garam masala. Fry the onion and ginger, add the tomatoes and spices with salt and cook until soft. Add the sprouts and half a cup of water, cover and cook 8 minutes until just tender.'),
  ('Mushroom Peas Curry', 'Indian', 25, 3, ARRAY['mushrooms', 'peas (matar)', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'turmeric (haldi)', 'garam masala'],
   'Fry the onion, add ginger and garlic, then the tomatoes, turmeric and salt into a masala. Add the sliced mushrooms and peas and cook 10 minutes. Finish with garam masala.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Mushroom Peas Curry. Indian dish, 25 minutes. Ingredients: mushrooms, peas (matar), onion, tomatoes, ginger (adrak), garlic, turmeric (haldi), garam masala. Fry the onion, add ginger and garlic, then the tomatoes, turmeric and salt into a masala. Add the sliced mushrooms and peas and cook 10 minutes. Finish with garam masala.'),
  ('Mixed Vegetable Curry', 'Indian', 30, 3, ARRAY['green beans', 'broccoli', 'peas (matar)', 'carrots', 'onion', 'tomatoes', 'turmeric (haldi)', 'coriander powder (dhania)'],
   'Fry the onion, add the tomatoes and spices with salt and cook until soft. Add the chopped vegetables and half a cup of water, cover and cook until just tender.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Mixed Vegetable Curry. Indian dish, 30 minutes. Ingredients: green beans, broccoli, peas (matar), carrots, onion, tomatoes, turmeric (haldi), coriander powder (dhania). Fry the onion, add the tomatoes and spices with salt and cook until soft. Add the chopped vegetables and half a cup of water, cover and cook until just tender.'),
  ('Sautéed Beans, Broccoli and Asparagus', 'Global', 15, 2, ARRAY['green beans', 'broccoli', 'asparagus', 'garlic', 'black pepper'],
   'Blanch the vegetables for 2 minutes. Sauté the garlic in a little oil, add the vegetables and toss on high heat for 3 minutes with salt and pepper.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Sautéed Beans, Broccoli and Asparagus. Global dish, 15 minutes. Ingredients: green beans, broccoli, asparagus, garlic, black pepper. Blanch the vegetables for 2 minutes. Sauté the garlic in a little oil, add the vegetables and toss on high heat for 3 minutes with salt and pepper.'),
  ('Cauliflower Peas Curry', 'Indian', 30, 3, ARRAY['cauliflower (gobi)', 'peas (matar)', 'onion', 'tomatoes', 'ginger (adrak)', 'turmeric (haldi)', 'coriander powder (dhania)', 'garam masala'],
   'Fry the onion and ginger, add the tomatoes and spices with salt. Add the cauliflower florets and peas with a splash of water, cover and cook 12 minutes until tender.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Cauliflower Peas Curry. Indian dish, 30 minutes. Ingredients: cauliflower (gobi), peas (matar), onion, tomatoes, ginger (adrak), turmeric (haldi), coriander powder (dhania), garam masala. Fry the onion and ginger, add the tomatoes and spices with salt. Add the cauliflower florets and peas with a splash of water, cover and cook 12 minutes until tender.'),
  ('Cauliflower Egg Curry', 'Indian', 35, 3, ARRAY['cauliflower (gobi)', 'eggs', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'turmeric (haldi)', 'garam masala'],
   'Hard-boil and peel 3 eggs. Make a masala with onion, ginger, garlic, tomatoes and spices. Add the cauliflower and a cup of water and cook until tender, then add the eggs and simmer 5 minutes.',
   false, true, true, true, true, true, 'starter', 'starter',
   'Cauliflower Egg Curry. Indian dish, 35 minutes. Ingredients: cauliflower (gobi), eggs, onion, tomatoes, ginger (adrak), garlic, turmeric (haldi), garam masala. Hard-boil and peel 3 eggs. Make a masala with onion, ginger, garlic, tomatoes and spices. Add the cauliflower and a cup of water and cook until tender, then add the eggs and simmer 5 minutes.'),
  ('Pumpkin Curry', 'Indian', 25, 3, ARRAY['pumpkin (kaddu)', 'mustard seeds (rai)', 'fenugreek seeds (methi)', 'green chilies (hari mirch)', 'turmeric (haldi)', 'amchur', 'jaggery'],
   'Crackle mustard and methi seeds in oil, add green chili, then the cubed pumpkin with turmeric and salt. Cover and cook on low until soft, then add amchur and a little jaggery and mash lightly.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Pumpkin Curry. Indian dish, 25 minutes. Ingredients: pumpkin (kaddu), mustard seeds (rai), fenugreek seeds (methi), green chilies (hari mirch), turmeric (haldi), amchur, jaggery. Crackle mustard and methi seeds in oil, add green chili, then the cubed pumpkin with turmeric and salt. Cover and cook on low until soft, then add amchur and a little jaggery and mash lightly.'),
  ('Bottle Gourd Dal', 'Indian', 30, 4, ARRAY['toor dal (arhar)', 'bottle gourd (lauki)', 'tomatoes', 'cumin seeds (jeera)', 'turmeric (haldi)', 'asafoetida (hing)'],
   'Pressure-cook the dal with the cubed bottle gourd, turmeric and salt. Crackle cumin and hing in oil, add the tomatoes and cook until soft, then stir in the dal and simmer 5 minutes.',
   true, true, true, false, true, true, 'starter', 'starter',
   'Bottle Gourd Dal. Indian dish, 30 minutes. Ingredients: toor dal (arhar), bottle gourd (lauki), tomatoes, cumin seeds (jeera), turmeric (haldi), asafoetida (hing). Pressure-cook the dal with the cubed bottle gourd, turmeric and salt. Crackle cumin and hing in oil, add the tomatoes and cook until soft, then stir in the dal and simmer 5 minutes.'),
  ('Ivy Gourd Fry', 'South Indian', 25, 2, ARRAY['ivy gourd (tindora)', 'mustard seeds (rai)', 'curry leaves (kadi patta)', 'turmeric (haldi)', 'red chili powder (lal mirch)'],
   'Slice the ivy gourd into thin rounds. Crackle mustard seeds and curry leaves, add the ivy gourd with turmeric and salt, and cook uncovered on medium, stirring, until tender and lightly crisp. Finish with chili powder.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Ivy Gourd Fry. South Indian dish, 25 minutes. Ingredients: ivy gourd (tindora), mustard seeds (rai), curry leaves (kadi patta), turmeric (haldi), red chili powder (lal mirch). Slice the ivy gourd into thin rounds. Crackle mustard seeds and curry leaves, add the ivy gourd with turmeric and salt, and cook uncovered on medium, stirring, until tender and lightly crisp. Finish with chili powder.'),
  ('Air-Fried Bhindi', 'Indian', 20, 2, ARRAY['okra (bhindi)', 'besan (gram flour)', 'red chili powder (lal mirch)', 'amchur', 'turmeric (haldi)'],
   'Slit the dry okra lengthwise and toss with besan, spices, salt and a teaspoon of oil. Air-fry at 190°C (375°F) for 12 to 14 minutes, shaking halfway, until crisp.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Air-Fried Bhindi. Indian dish, 20 minutes. Ingredients: okra (bhindi), besan (gram flour), red chili powder (lal mirch), amchur, turmeric (haldi). Slit the dry okra lengthwise and toss with besan, spices, salt and a teaspoon of oil. Air-fry at 190°C (375°F) for 12 to 14 minutes, shaking halfway, until crisp.'),
  ('Capsicum Stir Fry', 'Indian', 15, 2, ARRAY['bell peppers', 'onion', 'cumin seeds (jeera)', 'turmeric (haldi)', 'coriander powder (dhania)'],
   'Crackle the cumin, add sliced onion and bell peppers, and stir-fry on high with turmeric, coriander powder and salt for 5 minutes, keeping some crunch.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Capsicum Stir Fry. Indian dish, 15 minutes. Ingredients: bell peppers, onion, cumin seeds (jeera), turmeric (haldi), coriander powder (dhania). Crackle the cumin, add sliced onion and bell peppers, and stir-fry on high with turmeric, coriander powder and salt for 5 minutes, keeping some crunch.'),
  ('Low-Fat Paneer Stir Fry', 'Indian', 15, 2, ARRAY['low fat paneer', 'bell peppers', 'onion', 'black pepper', 'cumin seeds (jeera)'],
   'Stir-fry the cumin, sliced onion and bell peppers on high heat for 3 minutes. Add cubed paneer, salt and pepper and toss 2 minutes more.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Low-Fat Paneer Stir Fry. Indian dish, 15 minutes. Ingredients: low fat paneer, bell peppers, onion, black pepper, cumin seeds (jeera). Stir-fry the cumin, sliced onion and bell peppers on high heat for 3 minutes. Add cubed paneer, salt and pepper and toss 2 minutes more.'),
  ('Low-Fat Paneer Curry', 'Indian', 25, 3, ARRAY['low fat paneer', 'onion', 'tomatoes', 'ginger (adrak)', 'garlic', 'turmeric (haldi)', 'garam masala'],
   'Fry the onion, then ginger, garlic, tomatoes and spices into a thick masala. Add a cup of water and simmer 5 minutes, then add the paneer cubes and simmer 3 minutes.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Low-Fat Paneer Curry. Indian dish, 25 minutes. Ingredients: low fat paneer, onion, tomatoes, ginger (adrak), garlic, turmeric (haldi), garam masala. Fry the onion, then ginger, garlic, tomatoes and spices into a thick masala. Add a cup of water and simmer 5 minutes, then add the paneer cubes and simmer 3 minutes.'),
  ('Paneer Wraps', 'Indian', 20, 2, ARRAY['whole wheat roti', 'low fat paneer', 'onion', 'bell peppers', 'yogurt (dahi)', 'mint leaves (pudina)', 'chaat masala'],
   'Sear the paneer with sliced onion, peppers, chaat masala and salt. Mix the yogurt with chopped mint. Spread the mint yogurt on warm rotis, fill with the paneer and roll up.',
   true, true, true, false, false, true, 'starter', 'starter',
   'Paneer Wraps. Indian dish, 20 minutes. Ingredients: whole wheat roti, low fat paneer, onion, bell peppers, yogurt (dahi), mint leaves (pudina), chaat masala. Sear the paneer with sliced onion, peppers, chaat masala and salt. Mix the yogurt with chopped mint. Spread the mint yogurt on warm rotis, fill with the paneer and roll up.'),
  ('Sambar', 'South Indian', 40, 4, ARRAY['toor dal (arhar)', 'drumsticks', 'pumpkin (kaddu)', 'tomatoes', 'tamarind (imli)', 'sambar powder', 'mustard seeds (rai)', 'curry leaves (kadi patta)', 'asafoetida (hing)'],
   'Pressure-cook the dal until soft. Simmer the vegetables in tamarind water with sambar powder, tomatoes and salt until tender. Add the dal and simmer 10 minutes. Pour over a tempering of mustard seeds, curry leaves and hing.',
   true, true, true, false, true, true, 'starter', 'starter',
   'Sambar. South Indian dish, 40 minutes. Ingredients: toor dal (arhar), drumsticks, pumpkin (kaddu), tomatoes, tamarind (imli), sambar powder, mustard seeds (rai), curry leaves (kadi patta), asafoetida (hing). Pressure-cook the dal until soft. Simmer the vegetables in tamarind water with sambar powder, tomatoes and salt until tender. Add the dal and simmer 10 minutes. Pour over a tempering of mustard seeds, curry leaves and hing.'),
  ('Jowar Roti', 'Indian', 25, 3, ARRAY['jowar flour', 'warm water', 'salt'],
   'Knead the jowar flour with salt and warm water into a soft dough. Pat or roll each ball into a thin round between sheets, cook on a hot tawa, sprinkle with water, flip and puff over the flame.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Jowar Roti. Indian dish, 25 minutes. Ingredients: jowar flour, warm water, salt. Knead the jowar flour with salt and warm water into a soft dough. Pat or roll each ball into a thin round between sheets, cook on a hot tawa, sprinkle with water, flip and puff over the flame.'),
  ('Ragi Mudde', 'South Indian', 20, 2, ARRAY['ragi flour', 'water', 'salt'],
   'Bring 1 cup of water with salt to a boil. Add half a cup of ragi flour in a heap, cook 2 minutes without stirring, then mix hard with a flat spoon until smooth. Wet your hands and shape into balls. Serve with sambar or dal.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Ragi Mudde. South Indian dish, 20 minutes. Ingredients: ragi flour, water, salt. Bring 1 cup of water with salt to a boil. Add half a cup of ragi flour in a heap, cook 2 minutes without stirring, then mix hard with a flat spoon until smooth. Wet your hands and shape into balls. Serve with sambar or dal.'),
  ('Seed Mix Crackers', 'Global', 60, 6, ARRAY['flaxseeds', 'sunflower seeds', 'pumpkin seeds', 'sesame seeds', 'chia seeds', 'salt'],
   'Mix the seeds with salt and about 1 cup of water and rest 15 minutes until it binds. Spread thin on a lined tray and bake at 160°C (325°F) for 30 minutes. Score into squares, flip and bake 20 minutes more until crisp.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Seed Mix Crackers. Global dish, 60 minutes. Ingredients: flaxseeds, sunflower seeds, pumpkin seeds, sesame seeds, chia seeds, salt. Mix the seeds with salt and about 1 cup of water and rest 15 minutes until it binds. Spread thin on a lined tray and bake at 160°C (325°F) for 30 minutes. Score into squares, flip and bake 20 minutes more until crisp.'),
  ('Roasted Makhana', 'Indian', 10, 2, ARRAY['makhana', 'ghee', 'black pepper', 'turmeric (haldi)'],
   'Warm a teaspoon of ghee, add the makhana and roast on low for 6 to 8 minutes until crisp. Toss with salt, pepper and a pinch of turmeric.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Roasted Makhana. Indian dish, 10 minutes. Ingredients: makhana, ghee, black pepper, turmeric (haldi). Warm a teaspoon of ghee, add the makhana and roast on low for 6 to 8 minutes until crisp. Toss with salt, pepper and a pinch of turmeric.'),
  ('Baked Chickpeas', 'Global', 35, 2, ARRAY['canned chickpeas', 'red chili powder (lal mirch)', 'cumin seeds (jeera)'],
   'Pat the chickpeas very dry, toss with a teaspoon of oil, chili, ground cumin and salt, and bake or air-fry at 200°C (400°F) for 20 to 25 minutes until crunchy.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Baked Chickpeas. Global dish, 35 minutes. Ingredients: canned chickpeas, red chili powder (lal mirch), cumin seeds (jeera). Pat the chickpeas very dry, toss with a teaspoon of oil, chili, ground cumin and salt, and bake or air-fry at 200°C (400°F) for 20 to 25 minutes until crunchy.'),
  ('Carrot Cucumber Sticks with Hummus', 'Global', 5, 1, ARRAY['carrots', 'cucumber', 'hummus'],
   'Cut 100 g of carrot and cucumber into sticks and serve with 2 tablespoons of hummus.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Carrot Cucumber Sticks with Hummus. Global dish, 5 minutes. Ingredients: carrots, cucumber, hummus. Cut 100 g of carrot and cucumber into sticks and serve with 2 tablespoons of hummus.'),
  ('Stewed Apple with Cinnamon', 'Global', 15, 1, ARRAY['apple', 'cinnamon (dalchini)'],
   'Dice an apple and simmer it with a splash of water and a pinch of cinnamon for 8 to 10 minutes until soft.',
   true, true, true, true, true, true, 'starter', 'starter',
   'Stewed Apple with Cinnamon. Global dish, 15 minutes. Ingredients: apple, cinnamon (dalchini). Dice an apple and simmer it with a splash of water and a pinch of cinnamon for 8 to 10 minutes until soft.'),
  ('Black Sesame Jaggery Laddoo', 'Indian', 25, 10, ARRAY['black sesame seeds (til)', 'jaggery', 'cardamom (elaichi)', 'ghee'],
   'Dry-roast the sesame seeds until they crackle, then cool and pulse coarsely. Melt the jaggery with a spoon of ghee until bubbly, stir in the sesame and cardamom, and shape into small laddoos while warm.',
   true, true, true, true, false, true, 'starter', 'starter',
   'Black Sesame Jaggery Laddoo. Indian dish, 25 minutes. Ingredients: black sesame seeds (til), jaggery, cardamom (elaichi), ghee. Dry-roast the sesame seeds until they crackle, then cool and pulse coarsely. Melt the jaggery with a spoon of ghee until bubbly, stir in the sesame and cardamom, and shape into small laddoos while warm.')
ON CONFLICT (title) DO NOTHING;

SELECT count(*) AS recipes FROM recipes;   -- expect 112
